import { ClerkProvider } from "@clerk/nextjs"
import "../globals.css"


import { Inter } from "next/font/google"
import LeftSidebar from "@app/components/layouts/leftSideBar/page"
import MainContainer from "@app/components/layouts/mainContainer/page"
import RightSideBar from "@app/components/layouts/rightSideBar/page"
import BottomBar from "@app/components/layouts/bottomBar/page"
export const metadata = {
    title: 'Nextjs',
    description: 'Generated by Next'
}
const inter = Inter({ subsets: ['latin'] })
export default function RootLayout({ children }) {
    return (
        <ClerkProvider>
            <html lang="en">
                <body className={`${inter.className} bg-purple-2 text-light-1`}>
                    <main className="flex flex-row">
                        <LeftSidebar/>
                        <MainContainer>
                            {children}
                        </MainContainer>
                        <RightSideBar />
                    </main>
                    <BottomBar />
                </body>
            </html>

        </ClerkProvider>
    )
}